### ISSUE TITLE
Cannot get image or video thumbnail using media-thumbnail in node.js

### ISSUE THREAD

**Issue by rnithin133** [rajat1saxena/media-thumbnail#4]
This is my code below:
 ```
mt.forImage(
        "./media/hello.png",
        "./media/thumb/",
        {
            width: 100,
            height: 100,
            preserveAspectRatio: false
        })
        .then(result => {
            console.log('Success')
        }).catch(err => {
        console.error(err)
    });
```
and output is:
```
Error: Non-zero exit code
    at ChildProcess.convert.on.code (E:\projects\server\node_modules\media-thumbnail\index.js:61:16)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

whenever using this media-thumbnail I'm getting this same issue.
Please tell me how to solve this.
Thanks in advance :)

**Comment by rajat1saxena** [comment]
You need to have ffmpeg and imagemagick installed on your machine to use this package. See here: https://github.com/rajat1saxena/media-thumbnail#install
